### ISSUE TITLE
Two separate menus? Left / Right??

### ISSUE THREAD

**Issue by viva-ali** [jakiestfu/Snap.js#101]
Hey Jakie!

Mate, fantastic coding, hats off! Do you know if I can have two separate menus? Slide left for content 1, slide right for content 2, that sort of thing? I've been pulling my hair out trying to nail it.

Thanks!!! Ali

**Comment by jakiestfu** [comment]
The way it works is like so: You have two background drawers, a left and a right one with `.snap-drawer-left` and `.snap-drawer-right` classes respectively. If you slide the pane to the left, Snap.js will add a `.snapjs-right` class to the body which through the [CSS listed here](https://github.com/jakiestfu/Snap.js/blob/master/snap.css#L55-L68), will hide the left drawer, and reveal the right, and vice versa.

**Comment by dotnetwise** [comment]
If you would have any content in the `right` pane it never gets displayed in your demo page because of this:

``` css
/* Hide the actual "Right" drawer in the demo */
.snapjs-right .snap-drawer-right {
    display: none;
}

```

**Comment by jakiestfu** [comment]
Look at the ratchet example. It's very simple, the `.snapjs-right` and `.snapjs-left` classes dictate which drawer is open. From there, you can trickle down and show the appropriate content, so:

``` css
.snap-drawer-right,
.snap-drawer-left{
    display: none;
}

.snapjs-right .snap-drawer-right,
.snapjs-left .snap-drawer-left {
    display: block;
}
```

This shows the right and left drawers, respectively when the user drags them open.
