### ISSUE TITLE
Phonegap , Annoying Horizontal Scroll

### ISSUE THREAD

**Issue by greatcrypter** [jakiestfu/Snap.js#108]
How to remove the horizontal scroll bar when snapper open left?

![screen shot 2013-08-12 at 9 32 54 pm](https://f.cloud.github.com/assets/3822510/947454/bf2925b6-0353-11e3-9e65-6e6d4144c842.png)

**Comment by jakiestfu** [comment]
Try

``` css
body{
    overflow-x: hidden;
}
```
