### ISSUE TITLE
Disable body event and clicks when menu is open

### ISSUE THREAD

**Issue by vanilla38** [jakiestfu/Snap.js#174]
Hello, i want to disable all links and onclick events when menu is opened, i also wonder if it's possible to disable bod scrolling during this period. Thanks.

**Comment by scottgallant** [comment]
My solution for this was to add an empty div over the content area while the tray is open.  When the div is clicked, it hides itself and closes the menu.
**HTML**

``` html
<div class="drawers">
    <div class="left-drawer"></div>
    ...stuff
</div>
<div id="content">
    <div class="prevent-click"></div>
    ...stuff
</div>
```

**JS**

``` javascript
// create snapper, adds a class to body when open and closes when tapped
var snapper = new Snap({
    element: document.getElementById('content'),
    addBodyClasses: true,
    tapToClose: true
});
```

**CSS**

``` css
/* Empty div to prevent interaction with content */
div.prevent-click {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    background: transparent;
    z-index: 10;
    overflow: hidden;
    display: none;
}

/* Show the empty div when the tray is open (only using left tray in this example) */
body.snapjs-left div.prevent-click {
    display: block;
}
```

**JS**

``` javascript
// hide empty div when clicked
$('.prevent-click').live( "click", function() {
    $(".prevent-click").hide()
});
```
