### ISSUE TITLE
Drag does not work for fixed position element that is not nested in content

### ISSUE THREAD

**Issue by brendajin** [jakiestfu/Snap.js#86]
Drag becomes disabled when the #do-drag element becomes un-nested from #content (for example, for a fixed position sidebar that drags to reveal a menu). 

I believe this has to do with the parentNode settings. Is there a way around this?

Here is the HTML and CSS that can be applied to http://jakiestfu.github.io/Snap.js/demo/apps/dragElement.html#

``` html
<div id="content" class="snap-content" style="-webkit-transform: translate3d(266px, 0, 0);">
    <div id="toolbar"></div>
</div><div id="do-drag">Drag Handle</div>
```

``` css
#do-drag {
    position: fixed;
    top: 0;
    left: 0;
    width: 60px;
    height: 100%;
    z-index:3;
}
```
